# Generated by Django 4.1.6 on 2023-03-14 22:26

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_client_user_client_username_mssg_link_mssg_period_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Emails',
        ),
    ]
