# Generated by Django 4.1.6 on 2023-03-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_habit_time_fulfil'),
        ('mailing', '0006_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='andreymazo@mail.ru', max_length=50, verbose_name='Емэйл в форме сабджекта')),
                ('topic', models.CharField(default='ande', max_length=100, verbose_name='Тема сообщения в форме сабджекта')),
                ('text', models.CharField(default='and here', max_length=100, verbose_name='Текст')),
                ('period', models.IntegerField(choices=[(86400, '3min=120'), (604800, 'неделя=604800'), (2419200, 'месяц=2419200')], default=86400, verbose_name='Период')),
                ('status', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.habit')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
