# Generated by Django 4.1.6 on 2023-03-15 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('time_todo', models.TimeField(auto_now_add=True, verbose_name='время, когда необходимо выполнять привычку')),
                ('action', models.CharField(max_length=150, verbose_name='действие, которое представляет из себя привычка')),
                ('useful', models.BooleanField(blank=True, null=True, verbose_name='полезная привычка или нет')),
                ('period', models.CharField(max_length=100, verbose_name='периодичность выполнения привычки для напоминания в днях')),
                ('prize', models.CharField(max_length=150, verbose_name='чем пользователь должен себя вознаградить после выполнения')),
                ('time_fulfil', models.CharField(max_length=100, verbose_name='время, которое предположительно потратит пользователь на выполнение привычки')),
                ('is_published', models.BooleanField(blank=True, null=True, verbose_name='привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('if_connected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mustbewith_useful', to='users.habit', verbose_name='привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных')),
                ('if_pleasant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canbewith_useful', to='users.habit', verbose_name='привычка, которую можно привязать к выполнению полезной привычки')),
            ],
        ),
    ]
