# Generated by Django 4.1.6 on 2023-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_habit_options_alter_habit_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='периодичность выполнения привычки для напоминания в днях'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='prize',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='чем пользователь должен себя вознаградить после выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_fulfil',
            field=models.IntegerField(blank=True, null=True, verbose_name='время, которое предположительно потратит пользователь на выполнение привычки'),
        ),
    ]
