# Generated by Django 4.1.6 on 2023-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_habit_period_alter_habit_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(default='Nowhere', max_length=150, verbose_name='место'),
        ),
    ]
