# Generated by Django 4.1.6 on 2023-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_habit_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_fulfil',
            field=models.IntegerField(blank=True, max_length=120, null=True, verbose_name='время, которое предположительно потратит пользователь на выполнение привычки'),
        ),
    ]
