# Generated by Django 4.1.6 on 2023-03-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_habit_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='time_to_doo_habit',
            field=models.TimeField(blank=True, null=True, verbose_name='время, когда необходимо выполнять привычку'),
        ),
    ]
