# Generated by Django 4.1.6 on 2023-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=200, verbose_name='Фамилия Имя Отчество')),
                ('comment', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mssg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Тема')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
            ],
        ),
    ]
