# Generated by Django 4.1.6 on 2023-02-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mssg',
            name='period',
            field=models.TimeField(auto_now=True, choices=[(86400, 'день=86400'), (604800, 'неделя=604800'), (2419200, 'месяц=2419200')], max_length=10),
        ),
        migrations.AddField(
            model_name='mssg',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mssg',
            name='topic',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('status_complete', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Chtonibud comment')),
            ],
        ),
    ]
