# Generated by Django 4.1.6 on 2023-02-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mssg_period_mssg_status_alter_mssg_topic_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailinglog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing', models.CharField(max_length=100, verbose_name='Email')),
                ('result', models.CharField(max_length=100, verbose_name='Result')),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emails',
            name='comment',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Какому клиенту относится'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Емэйл'),
        ),
        migrations.AlterField(
            model_name='mssg',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='mssg',
            name='topic',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Какому клиенту относится'),
        ),
    ]
