# Generated by Django 4.1.6 on 2023-02-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailinglog_alter_client_options_alter_client_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name': 'Емэйл', 'verbose_name_plural': 'Емэйлы'},
        ),
        migrations.RenameField(
            model_name='mssg',
            old_name='topic',
            new_name='link',
        ),
    ]
