# Generated by Django 4.1.6 on 2023-03-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_managers_delete_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mssg',
        ),
    ]
